### ISSUE TITLE
Would like darker version of this theme.

### ISSUE THREAD

**Issue by the-r3dacted** [SlippingGitty/Discord-2012-Theme#1]
I don't like how bright some of the gradients get, and I'd prefer them to be a bit darker, so I'd like a modded version like that.

**Comment by SlippingGitty** [comment]
Thanks for taking interest in my theme! Though I personally have no plans to change major parts of this theme nor create a second variation, I am open to anyone forking this repository and making their own modifications. 

As always, you can find the main source to this theme here: https://github.com/SlippingGitty/slippinggitty.github.io/blob/main/SlideToUnlock.css
